import Link from "next/link";
import { fetchAnalytics, fetchSpots } from "@/lib/data";
import { hasPublicEnv } from "@/lib/supabase";
import { MoodDonut } from "@/components/MoodDonut";
export const dynamic="force-dynamic"; export const revalidate=0;

export default async function HomePage(){
  const fallback={totalReviews:0,avgRating:0,spotsCount:0,sentiment:{positive:0,mixed:0,negative:0},wording:{positive:0,mixed:0,negative:0},bySpot:[],recent:[]};
  const [spots,analytics]=hasPublicEnv()?await Promise.all([fetchSpots(),fetchAnalytics()]):[[],fallback];
  const total=analytics.totalReviews||1;
  const positive=Math.round(analytics.sentiment.positive/total*100);
  const mixed=Math.round(analytics.sentiment.mixed/total*100);
  const negative=Math.max(0,100-positive-mixed);
  const featured=spots.filter(s=>s.featured);
  const top=analytics.bySpot.filter(s=>s.count>0).slice(0,3);
  return <div className="page-shell pb-10">
    <section className="hero-stage"><div className="hero-grid">
      <div className="hero-copy"><p className="eyebrow">A living picture of Daet</p><h1 className="mt-3">How does Daet feel today?</h1><p className="mt-5 text-base leading-relaxed">Every visitor chooses a feeling. Every feeling becomes part of a living picture of the town.</p><div className="hero-actions"><Link href="/spots" className="btn-primary hero-cta">Leave a pulse <span>→</span></Link><Link href="/dashboard" className="btn-secondary hero-cta">Open live dashboard</Link></div><div className="hero-meta"><span>● Emoji is the official pulse</span><span>◎ No visitor account</span><span>◒ Community voices</span></div></div>
      <div className="hero-mood"><div className="hero-mood-top"><span><i className="live-dot"/> LIVE MOOD</span><span>{analytics.totalReviews} pulses</span></div><div className="hero-mood-chart"><MoodDonut positive={analytics.sentiment.positive} mixed={analytics.sentiment.mixed} negative={analytics.sentiment.negative} size={250}/><div className="hero-mood-overlay"><strong>{positive}%</strong><span>positive</span></div></div><div className="hero-mood-stats"><div><b>🙂</b><strong>{analytics.sentiment.positive}</strong><span>positive</span></div><div><b>😐</b><strong>{analytics.sentiment.mixed}</strong><span>mixed</span></div><div><b>😞</b><strong>{analytics.sentiment.negative}</strong><span>needs care</span></div></div><div className="hero-mood-track"><span style={{width:`${positive}%`}}/><span style={{width:`${mixed}%`}}/><span style={{width:`${negative}%`}}/></div></div>
    </div></section>
    <div className="metric-row"><div className="metric"><div className="label">Visitor pulses</div><div className="value">{analytics.totalReviews}</div><div className="hint">Shared across Daet</div></div><div className="metric"><div className="label">Average score</div><div className="value">{analytics.avgRating?analytics.avgRating.toFixed(1):"—"}</div><div className="hint">Optional secondary signal</div></div><div className="metric"><div className="label">Places tracked</div><div className="value">{spots.length}</div><div className="hint">Destinations in the pulse</div></div></div>
    <section className="section-space"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Explore the town</p><h2 className="mt-2">Places people are feeling</h2></div><Link href="/spots" className="text-xs font-extrabold text-[var(--teal)]">View all →</Link></div><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{featured.map(s=>{const st=analytics.bySpot.find(x=>x.id===s.id);return <Link key={s.id} href={`/spots/${s.slug}`} className="spot-card"><div className="spot-media" style={{backgroundImage:s.cover_url?`url(${s.cover_url})`:undefined}}/><div className="spot-card-body"><p className="spot-tag">{s.category}{s.barangay?` · ${s.barangay}`:""}</p><h3 className="mt-2">{s.name}</h3><p className="mt-2 line-clamp-2 text-xs leading-relaxed text-[var(--muted)]">{s.description}</p><div className="spot-rating"><span>{st?.count?`${st.count} visitor pulses`:"No pulses yet"}</span><strong>{st?.count?st.avg.toFixed(1):"—"}</strong></div></div></Link>})}{featured.length===0&&<p className="text-sm text-[var(--muted)]">Add featured destinations in the officer desk to showcase them here.</p>}</div></section>
    {top.length>0&&<section className="surface px-5 py-6 sm:px-8"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">What is resonating</p><h2 className="mt-2">The places leading the pulse</h2></div><Link href="/dashboard" className="text-xs font-extrabold text-[var(--teal)]">Open analytics →</Link></div><div className="mt-5 grid gap-4 md:grid-cols-3">{top.map((s,i)=><Link key={s.id} href={`/spots/${s.slug}`} className="group flex items-start gap-4 py-3"><span className="font-display text-3xl text-[#b6c3c0]">0{i+1}</span><span><strong className="block text-sm group-hover:text-[var(--teal)]">{s.name}</strong><span className="mt-1 block text-[11px] text-[var(--muted)]">{s.avg.toFixed(1)} average · {s.count} pulses</span></span></Link>)}</div></section>}
  </div>
}
