/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/board'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as LiveRouteImport } from './routes/live'
import { Route as SpotsRouteImport } from './routes/spots'
import { Route as TransmitRouteImport } from './routes/transmit'
import { Route as BoardIndexRouteImport } from './routes/board.index'
import { Route as BoardFacesRouteImport } from './routes/board.faces'
import { Route as BoardWordsRouteImport } from './routes/board.words'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskBoardRouteImport } from './routes/desk.board'
import { Route as DeskChannelsRouteImport } from './routes/desk.channels'
import { Route as DeskLogRouteImport } from './routes/desk.log'
import { Route as DeskWishesRouteImport } from './routes/desk.wishes'
import { Route as SpotsSlugRouteImport } from './routes/spots_.$slug'
import { Route as BoardFacesSlugRouteImport } from './routes/board.faces.$slug'
import { Route as BoardWordsSlugRouteImport } from './routes/board.words.$slug'
import { Route as DeskWishesIdRouteImport } from './routes/desk.wishes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotsRoute = SpotsRouteImport.update({
  id: '/spots',
  path: '/spots',
  getParentRoute: () => rootRouteImport,
} as any)
const TransmitRoute = TransmitRouteImport.update({
  id: '/transmit',
  path: '/transmit',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardRoute,
} as any)
const BoardFacesRoute = BoardFacesRouteImport.update({
  id: '/faces',
  path: '/faces',
  getParentRoute: () => BoardRoute,
} as any)
const BoardWordsRoute = BoardWordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => BoardRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskBoardRoute = DeskBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => DeskRoute,
} as any)
const DeskChannelsRoute = DeskChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => DeskRoute,
} as any)
const DeskLogRoute = DeskLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => DeskRoute,
} as any)
const DeskWishesRoute = DeskWishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => DeskRoute,
} as any)
const SpotsSlugRoute = SpotsSlugRouteImport.update({
  id: '/spots_/$slug',
  path: '/spots/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardFacesSlugRoute = BoardFacesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BoardFacesRoute,
} as any)
const BoardWordsSlugRoute = BoardWordsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BoardWordsRoute,
} as any)
const DeskWishesIdRoute = DeskWishesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeskWishesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/desk': typeof DeskRouteWithChildren
  '/live': typeof LiveRoute
  '/spots': typeof SpotsRoute
  '/transmit': typeof TransmitRoute
  '/board/faces': typeof BoardFacesRouteWithChildren
  '/board/words': typeof BoardWordsRouteWithChildren
  '/desk/board': typeof DeskBoardRoute
  '/desk/channels': typeof DeskChannelsRoute
  '/desk/log': typeof DeskLogRoute
  '/desk/wishes': typeof DeskWishesRouteWithChildren
  '/spots/$slug': typeof SpotsSlugRoute
  '/board/': typeof BoardIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/board/faces/$slug': typeof BoardFacesSlugRoute
  '/board/words/$slug': typeof BoardWordsSlugRoute
  '/desk/wishes/$id': typeof DeskWishesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/spots': typeof SpotsRoute
  '/transmit': typeof TransmitRoute
  '/board/faces': typeof BoardFacesRouteWithChildren
  '/board/words': typeof BoardWordsRouteWithChildren
  '/desk/board': typeof DeskBoardRoute
  '/desk/channels': typeof DeskChannelsRoute
  '/desk/log': typeof DeskLogRoute
  '/desk/wishes': typeof DeskWishesRouteWithChildren
  '/spots/$slug': typeof SpotsSlugRoute
  '/board': typeof BoardIndexRoute
  '/desk': typeof DeskIndexRoute
  '/board/faces/$slug': typeof BoardFacesSlugRoute
  '/board/words/$slug': typeof BoardWordsSlugRoute
  '/desk/wishes/$id': typeof DeskWishesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/desk': typeof DeskRouteWithChildren
  '/live': typeof LiveRoute
  '/spots': typeof SpotsRoute
  '/transmit': typeof TransmitRoute
  '/board/faces': typeof BoardFacesRouteWithChildren
  '/board/words': typeof BoardWordsRouteWithChildren
  '/desk/board': typeof DeskBoardRoute
  '/desk/channels': typeof DeskChannelsRoute
  '/desk/log': typeof DeskLogRoute
  '/desk/wishes': typeof DeskWishesRouteWithChildren
  '/spots_/$slug': typeof SpotsSlugRoute
  '/board/': typeof BoardIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/board/faces/$slug': typeof BoardFacesSlugRoute
  '/board/words/$slug': typeof BoardWordsSlugRoute
  '/desk/wishes/$id': typeof DeskWishesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/desk'
    | '/live'
    | '/spots'
    | '/transmit'
    | '/board/faces'
    | '/board/words'
    | '/desk/board'
    | '/desk/channels'
    | '/desk/log'
    | '/desk/wishes'
    | '/spots/$slug'
    | '/board/'
    | '/desk/'
    | '/board/faces/$slug'
    | '/board/words/$slug'
    | '/desk/wishes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live'
    | '/spots'
    | '/transmit'
    | '/board/faces'
    | '/board/words'
    | '/desk/board'
    | '/desk/channels'
    | '/desk/log'
    | '/desk/wishes'
    | '/spots/$slug'
    | '/board'
    | '/desk'
    | '/board/faces/$slug'
    | '/board/words/$slug'
    | '/desk/wishes/$id'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/desk'
    | '/live'
    | '/spots'
    | '/transmit'
    | '/board/faces'
    | '/board/words'
    | '/desk/board'
    | '/desk/channels'
    | '/desk/log'
    | '/desk/wishes'
    | '/spots_/$slug'
    | '/board/'
    | '/desk/'
    | '/board/faces/$slug'
    | '/board/words/$slug'
    | '/desk/wishes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
  DeskRoute: typeof DeskRouteWithChildren
  LiveRoute: typeof LiveRoute
  SpotsRoute: typeof SpotsRoute
  TransmitRoute: typeof TransmitRoute
  SpotsSlugRoute: typeof SpotsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spots': {
      id: '/spots'
      path: '/spots'
      fullPath: '/spots'
      preLoaderRoute: typeof SpotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmit': {
      id: '/transmit'
      path: '/transmit'
      fullPath: '/transmit'
      preLoaderRoute: typeof TransmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/'
      fullPath: '/board/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof BoardRoute
    }
    '/board/faces': {
      id: '/board/faces'
      path: '/faces'
      fullPath: '/board/faces'
      preLoaderRoute: typeof BoardFacesRouteImport
      parentRoute: typeof BoardRoute
    }
    '/board/words': {
      id: '/board/words'
      path: '/words'
      fullPath: '/board/words'
      preLoaderRoute: typeof BoardWordsRouteImport
      parentRoute: typeof BoardRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/board': {
      id: '/desk/board'
      path: '/board'
      fullPath: '/desk/board'
      preLoaderRoute: typeof DeskBoardRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/channels': {
      id: '/desk/channels'
      path: '/channels'
      fullPath: '/desk/channels'
      preLoaderRoute: typeof DeskChannelsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/log': {
      id: '/desk/log'
      path: '/log'
      fullPath: '/desk/log'
      preLoaderRoute: typeof DeskLogRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/wishes': {
      id: '/desk/wishes'
      path: '/wishes'
      fullPath: '/desk/wishes'
      preLoaderRoute: typeof DeskWishesRouteImport
      parentRoute: typeof DeskRoute
    }
    '/spots_/$slug': {
      id: '/spots_/$slug'
      path: '/spots/$slug'
      fullPath: '/spots/$slug'
      preLoaderRoute: typeof SpotsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/faces/$slug': {
      id: '/board/faces/$slug'
      path: '/$slug'
      fullPath: '/board/faces/$slug'
      preLoaderRoute: typeof BoardFacesSlugRouteImport
      parentRoute: typeof BoardFacesRoute
    }
    '/board/words/$slug': {
      id: '/board/words/$slug'
      path: '/$slug'
      fullPath: '/board/words/$slug'
      preLoaderRoute: typeof BoardWordsSlugRouteImport
      parentRoute: typeof BoardWordsRoute
    }
    '/desk/wishes/$id': {
      id: '/desk/wishes/$id'
      path: '/$id'
      fullPath: '/desk/wishes/$id'
      preLoaderRoute: typeof DeskWishesIdRouteImport
      parentRoute: typeof DeskWishesRoute
    }
  }
}

interface BoardFacesRouteChildren {
  BoardFacesSlugRoute: typeof BoardFacesSlugRoute
}

const BoardFacesRouteChildren: BoardFacesRouteChildren = {
  BoardFacesSlugRoute: BoardFacesSlugRoute,
}

const BoardFacesRouteWithChildren = BoardFacesRoute._addFileChildren(
  BoardFacesRouteChildren,
)

interface BoardWordsRouteChildren {
  BoardWordsSlugRoute: typeof BoardWordsSlugRoute
}

const BoardWordsRouteChildren: BoardWordsRouteChildren = {
  BoardWordsSlugRoute: BoardWordsSlugRoute,
}

const BoardWordsRouteWithChildren = BoardWordsRoute._addFileChildren(
  BoardWordsRouteChildren,
)

interface BoardRouteChildren {
  BoardFacesRoute: typeof BoardFacesRouteWithChildren
  BoardWordsRoute: typeof BoardWordsRouteWithChildren
  BoardIndexRoute: typeof BoardIndexRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardFacesRoute: BoardFacesRouteWithChildren,
  BoardWordsRoute: BoardWordsRouteWithChildren,
  BoardIndexRoute: BoardIndexRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

interface DeskWishesRouteChildren {
  DeskWishesIdRoute: typeof DeskWishesIdRoute
}

const DeskWishesRouteChildren: DeskWishesRouteChildren = {
  DeskWishesIdRoute: DeskWishesIdRoute,
}

const DeskWishesRouteWithChildren = DeskWishesRoute._addFileChildren(
  DeskWishesRouteChildren,
)

interface DeskRouteChildren {
  DeskBoardRoute: typeof DeskBoardRoute
  DeskChannelsRoute: typeof DeskChannelsRoute
  DeskLogRoute: typeof DeskLogRoute
  DeskWishesRoute: typeof DeskWishesRouteWithChildren
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskBoardRoute: DeskBoardRoute,
  DeskChannelsRoute: DeskChannelsRoute,
  DeskLogRoute: DeskLogRoute,
  DeskWishesRoute: DeskWishesRouteWithChildren,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
  DeskRoute: DeskRouteWithChildren,
  LiveRoute: LiveRoute,
  SpotsRoute: SpotsRoute,
  TransmitRoute: TransmitRoute,
  SpotsSlugRoute: SpotsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
